[package]
name = "updater"
version = "0.1.0"
authors = ["Ahmed Masud <ahmed.masud@saf.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
